build/lib.linux-x86_64-2.7/fast_cycle_solver.so: fast_cycle.cpp cycle.h setup.py
	python setup.py build
	cp build/lib.linux-x86_64-2.7/fast_cycle_solver.so ../../

clean:
	rm build/lib.linux-x86_64-2.7/fast_cycle_solver.so
